"""Dashboard: a static, server-less site for GitHub Pages.

Renders the **candidate board** (Phase 1 is ungraded -- no leaderboard yet), today's
intended trades, P&L vs the risk-free cash baseline, and the cost-sensitivity table.
Generated by the post-close job. See docs/DESIGN.md, "Dashboard".
"""

from dashboard.render import render_site

__all__ = ["render_site"]
